services:

  webapp:
    build:
      context: webapp/
      dockerfile: Dockerfile
    container_name: webapp_container
    ports:
      - "8050:8050"
      # - "8888:8888" # uncomment if you want to run jupyter for testing
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    user: "${UID}:${GID}"
    volumes:
      # - ./webapp/:/webapp # uncomment if you want changes to takes effect directly
      - ~/archives_collection_images:/images

  celery:
    build:
      context: webapp/
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A src.main.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
    user: "${UID}:${GID}"
    volumes:
      # - ./webapp/:/webapp # uncomment if you want changes to takes effect directly
      - ~/archives_collection_images:/images

  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc: 65535
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ~/archives_collection_images:/images

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"


  # embedding:
  #   build:
  #     context: embedding/
  #     dockerfile: Dockerfile
  #   container_name: embedding_container
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./embedding/:/embedding

  precommit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: precommit_container
    volumes:
      - .:/workspace
      - .git:/workspace/.git
    working_dir: /workspace

volumes:
  postgres_data:
