services:

  webapp:
    build:
      context: webapp/
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - db
      - embedding
    env_file:
      - .env
    volumes:
      - ./webapp/:/webapp


  db:
    image: pgvector/pgvector:pg14
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  embedding:
    build:
      context: embedding/
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - ./embedding/:/embedding

  precommit:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - .git:/workspace/.git
    working_dir: /workspace

volumes:
  postgres_data:
