services:

  webapp_base: &webapp_base
    build:
      context: webapp/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SELENIUM_REMOTE_URL=http://selenium:4444
    depends_on:
      - db
      - redis
    user: "${UID}:${GID}"
    volumes:
      - ./webapp/:/webapp
      - ~/archives_collection_images:/images

  webapp:
    <<: *webapp_base
    container_name: webapp_container
    ports:
      - "8050:8050"
      - "8888:8888"

  celery:
    <<: *webapp_base
    container_name: celery_worker
    command: celery -A src.main.celery_app.celery_app worker --loglevel=info
    cpu_period: 100000
    cpu_quota: 1000000

  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc: 65535
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ~/archives_collection_images:/images

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"

  precommit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: precommit_container
    volumes:
      - .:/workspace
      - .git:/workspace/.git
    working_dir: /workspace

volumes:
  postgres_data:
