services:

  webapp_base: &webapp_base
    build:
      context: webapp/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - EMBED_URL=http://embedding:8000/embed
    depends_on:
      - db
      - redis
      - embedding
    user: "${UID}:${GID}"
    volumes:
      - ./webapp/:/webapp
      - ~/archives_collection_images:/images

  webapp:
    <<: *webapp_base
    container_name: webapp_container
    ports:
      - "8050:8050"
      - "8888:8888"

  celery:
    <<: *webapp_base
    container_name: celery_worker
    command: celery -A src.main.celery_app.celery_app worker --loglevel=info
    cpu_period: 100000
    cpu_quota: 1000000

  db:
    image: pgvector/pgvector:pg14
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc: 65535
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ~/archives_collection_images:/images

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"

  embedding:
    container_name: embedding_container
    build:
      context: embedding/
      dockerfile: Dockerfile
      args:
        torch_cuda_arch_list: ""
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - ./embedding/:/embedding

  precommit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: precommit_container
    volumes:
      - .:/workspace
      - .git:/workspace/.git
    working_dir: /workspace

volumes:
  postgres_data:
