services:

  webapp_base: &webapp_base
    build:
      context: webapp/
      dockerfile: Dockerfile
      args:
        HOST_UID: "${UID}"
        HOST_GID: "${GID}"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - EMBED_URL=http://embedding:8000/v1/embeddings
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      embedding:
        condition: service_healthy

    volumes:
      - ./webapp/:/webapp
      - ~/archives_collection_images:/images

  webapp:
    <<: *webapp_base
    ports:
      - "8050:8050"
      - "8888:8888"

  celery:
    <<: *webapp_base
    command: celery -A src.main.celery_app.celery_app worker --loglevel=debug
    cpu_period: 100000
    cpu_quota: 1000000

  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      HNSW_EF_SEARCH: ${HNSW_EF_SEARCH}
    command: >
      postgres
      -c shared_buffers=6GB
      -c effective_cache_size=8GB
      -c work_mem=64MB
      -c maintenance_work_mem=512MB
      -c max_connections=200
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c autovacuum_max_workers=3
      -c autovacuum_naptime=30s
      -c max_wal_size=2GB
      -c min_wal_size=1GB
      -c log_min_duration_statement=4000
    shm_size: 4gb
    deploy:
      resources:
        limits:
          memory: 8GB
        reservations:
          memory: 4GB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  pgbouncer:
    image: bitnami/pgbouncer:latest
    environment:
      PGBOUNCER_DATABASE: ${POSTGRES_DB}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      PGBOUNCER_PORT: 5432
      PGBOUNCER_POOL_MODE: transaction
      PGBOUNCER_MAX_CLIENT_CONN: 1000
      PGBOUNCER_DEFAULT_POOL_SIZE: 25
    ports:
      - "5433:5432"
    depends_on:
      - db
    restart: unless-stopped

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"

  embedding:
    build:
      context: embedding/
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        EMBEDDING_MODE: ${EMBEDDING_MODE}
        torch_cuda_arch_list: ""
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./embedding/:/embedding
      - hf_cache:/root/.cache/huggingface

  precommit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: precommit_container
    volumes:
      - .:/workspace
      - .git:/workspace/.git
    working_dir: /workspace

volumes:
  postgres_data:
  hf_cache:
